### ISSUE TITLE
Correction des URL du MOS en asipsante.fr

### ISSUE THREAD

**Issue by ljoubert** [ansforge/ModelisationFHIRdesacteursdesante#2]
Bonjour,

la modélisation FHIR des données de santé fait référence à des URL en asipsante.fr qui ne sont plus à jour et sans que les redirections à partir de esante.gouv.fr fonctionnent. Exemple:
 - Natures du cycle de formation des professionnels du RASS, http://mos.asipsante.fr/NOS/TABS/JDV_J86-NatCycleForm-RASS.tabs
 - Discipline à laquelle l'autorisation d'exercice est restreinte dans le RASS;http://mos.asipsante.fr/NOS/TABS/JDV_J76-DisciplineAutorisation-RASS.tabs
 - Civilité : http://mos.asipsante.fr/NOS/TABS/JDV_J78-Civilite-RASS.tabs 
 - Civilité Exercice : http://mos.asipsante.fr/NOS/TABS/JDV_J79-CiviliteExercice-RASS.tabs
 - etc.

Merci beaucoup,

Laurent

**Comment by mchaabaoui** [comment]
C'est corrigé.
"contact": [
    {
      "name": "monserviceclient.annuaire@esante.gouv.fr"
    }
  ],
